name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: awshost-label-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: echo ${{ secrets.ENV_VAR }} > .env
        
      - name: Build project
        run: npm run build

      - name: Docker build
        run: docker build -t ecomapi:latest .

      - name: Docker run
        run: |
          docker run -d \
            --name ecomapi \
            -p 3000:3000 \
            ecomapi:latest
